### ISSUE TITLE
distorm not found

### ISSUE THREAD

**Issue by Leo675** [packz/ropeme#3]
Hey there packz. I was trying out ROPme and it didn't work because distorm is now distorm3.

I'm installing distorm from python pip and there is no other one.

I was able to fix this by changing the import on gadgets.py from

import distorm

to

import distorm3 as distorm

This issue may not be present on older systems as I am running python 2.7.5 and pip 6.0.6 on CentOS7

**Comment by packz** [comment]
Fixed with #2
